### ISSUE TITLE
Emoji doesn't render for typst `\u{27A1}`

### ISSUE THREAD

**Issue by youwuyou** [polazarus/typst-svg-emoji#7] opened 2024-04-09 17:11 UTC
I was trying to use the right arrow emoji, i.e with the escape code `\u{27A1}` named `arrow.r.filled` as specified under official typst document [here](https://typst.app/docs/reference/symbols/emoji/) and it does not seem to work unfortunately, while the other emojis are rendered correctly when I export the pdf.

![image](https://github.com/polazarus/typst-svg-emoji/assets/82619264/b6778e8e-fbdb-49d0-9fa8-73995335e96c)

Here is my web workspace view, it seems to me that the typst is using the "Right Arrow on Twitter / X Twemoji 15.0.1" variant instead?

![image](https://github.com/polazarus/typst-svg-emoji/assets/82619264/9dcbe79d-58da-4bbc-b9b6-1260f3d86c7a)

Thanks for the great work!

**Comment by polazarus** [comment] 2024-04-10 14:35
~~**Noto Color Emoji** (the only font supported for now) does not implement it. And I don't why it should either: this symbol is a Black Rightwards Arrow... so no color ;)
One way to support it would be to add more symbols from **Noto [] Emoji** for instance.~~

~~PS: I don't see why Twemoji defines it in blue?!~~

my bad! will investigate it

**Comment by polazarus** [comment] 2024-04-10 20:08
After looking into it, it's "a feature not a bug"!

So yes `\u{27A1}` is not truly an emoji. A classic font may provide a classic fat arrow for it.
But the sequence `\u{27A1}\u{FE0F}` (variation selector 16) is definitely one.
Most emoji picker will input the sequence when asking for the right arrow.

I had to actually care about emoji sequences because for Noto Emoji: 0, 1, ... are emoji too .

IMO Typst should change the definition of `#emoji.arrow.r.filled`.

**Comment by polazarus** [comment] 2024-04-10 20:21
Reported to typst [#3915](https://github.com/typst/codex/issues/23)
Wontfix on my part

**Closed as completed by polazarus** 2024-04-10 20:21 UTC
